name: Check Commit Messages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-commit-messages:
    name: Check commit messages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      # with:
      #   ref: ${{ github.event.pull_request.head.sha }}
      #   fetch-depth: 0

    - name: Test
      env:
        BASE_REF: ${{ github.base_ref }}
      run: echo "asdf $BASE_REF"
    - run: echo "ASDF"
